//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ck()
        {
            this.th = new HashSet<th>();
        }
    
        public int ckID { get; set; }
        public string CkType { get; set; }
        public int Ckclient { get; set; }
        public int Sum { get; set; }
        public double Price { get; set; }
        public string check1 { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<th> th { get; set; }
    }
}
