//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warehouseEntities : DbContext
    {
        public warehouseEntities()
            : base("name=warehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<AdminStatus> AdminStatus { get; set; }
        public virtual DbSet<bs> bs { get; set; }
        public virtual DbSet<ck> ck { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<Dtable> Dtable { get; set; }
        public virtual DbSet<measure> measure { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<rk> rk { get; set; }
        public virtual DbSet<storage1> storage1 { get; set; }
        public virtual DbSet<storageType> storageType { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<th> th { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<yk> yk { get; set; }
    }
}
