//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rk
    {
        public int ID { get; set; }
        public string rkType { get; set; }
        public int rkSupplier { get; set; }
        public int Sum { get; set; }
        public double Price { get; set; }
        public string check1 { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
