//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.rk = new HashSet<rk>();
        }
    
        public int supplierID { get; set; }
        public string supplierType { get; set; }
        public string supplierName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string supplier_contact { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rk> rk { get; set; }
    }
}
